apiVersion: apps/v1
kind: Deployment
metadata: { name: smartpole-cloud }
spec:
  replicas: 1
  selector: { matchLabels: { app: smartpole-cloud } }
  template:
    metadata: { labels: { app: smartpole-cloud } }
    spec:
      containers:
        - name: cloud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{ containerPort: 8000 }]
          env:
            - { name: DATABASE_URL, value: sqlite:///./smartpole.db }
            - { name: POLICY_FILE, value: cloud/policy/rules.yaml }
---
apiVersion: v1
kind: Service
metadata: { name: smartpole-cloud }
spec:
  selector: { app: smartpole-cloud }
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
