replicaCount: 2
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
pdb:
  enabled: true
  minAvailable: 1
serviceMonitor:
  enabled: false
  namespace: monitoring
