name: CI

on:
  push:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install system packages OpenCV & Tesseract need
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libglib2.0-0 libgl1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q
